targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true
        generate_for:
          - "lib/**/entities/**.dart"

      json_serializable|json_serializable:
        enabled: true
        generate_for:
          - "lib/**/entities/**.dart"

        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true